
xdebug.idekey = PHPSTORM

xdebug.remote_handler=dbgp
xdebug.mode=debug,profile
xdebug.start_with_request=trigger
xdebug.client_host=${XDEBUG_HOST}
xdebug.client_port=${XDEBUG_PORT}
xdebug.remote_port=${XDEBUG_PORT}
xdebug.output_dir=${XDEBUG_OUT}
# xdebug.log=/dev/stdout
xdebug.discover_client_host = false

# xdebug.remote_log='/tmp/xdebug.log'
# Get remote ip mac: ipconfig getifaddr en0
xdebug.max_nesting_level = ${XDEBUG_MAX_NESTING_LEVEL}