FROM nvcr.io/nvidia/pytorch:24.08-py3-igpu

# ENV NODEJS_VERSION=16
ENV TZ=UTC \
    DEBIAN_FRONTEND=noninteractive

# CHANGE ON OWN USER/GROUP IDS [$ id]
RUN usermod -u 1000 www-data
RUN groupmod -g 1000 www-data
RUN usermod -G staff www-data

# # Woraround in latest images in order to install php-pear
# # https://github.com/docker-library/php/blob/master/Dockerfile-debian.template#L3-L10
# RUN rm /etc/apt/preferences.d/no-debian-php

# install core extension
RUN apt-get update \
    && apt-get install -y --no-install-recommends apt-utils \
        curl \
        git \
        bzip2 \
        unzip \
        zip \
        libcurl4-openssl-dev \
        ghostscript \
        libmcrypt-dev \
        libssl-dev \
        libzip-dev \
        libpng-dev \
        libjpeg-dev \
        libxml2-dev \
        zlib1g-dev \
        libicu-dev \
        libpq-dev \
        libxslt-dev \
        libc-client-dev \
        libkrb5-dev \
        libxslt1-dev \
        libmemcached-dev \
        libldap2-dev \
        geoip-bin \
        geoip-database \
        libfreetype6-dev \
        # libjpeg62-turbo-dev \
        libfreetype6-dev \
        libgeoip-dev \
        gettext \
        default-mysql-client \
        libmagickwand-dev \
        libicu-dev \
        libtidy-dev \
        libwebp-dev \
        libusb-1.0-0 \
        libgl1 \
        jpegoptim \
        pngquant \
        acl \
        procps \
        python3.10-venv \
        software-properties-common \
    && apt-get clean

RUN add-apt-repository ppa:ondrej/php

RUN apt-get install -y --no-install-recommends php8.5-cli php8.5-imap php8.5-gd \
    php8.5-bcmath php8.5-bz2 php8.5-calendar php8.5-curl php8.5-exif php8.5-fileinfo php8.5-gettext php8.5-intl \
    php8.5-shmop php8.5-soap php8.5-sockets php8.5-sysvmsg php8.5-sysvsem php8.5-sysvshm php8.5-xml php8.5-xsl php8.5-zip php8.5-tidy \
    php8.5-opcache php8.5-pdo php8.5-pgsql php8.5-apcu php8.5-mbstring \
    && apt-get clean

RUN apt-get install -y php8.5-dev \
    && apt-get clean

RUN apt-get install -y php-pear \
    && apt-get clean

RUN pecl channel-update pecl.php.net

RUN python3 -m pip install --upgrade pip

# # RUN pecl install redis http://pecl.php.net/get/geoip-1.1.1.tgz \
# #     && docker-php-ext-enable redis geoip

#services
RUN apt-get install -y --no-install-recommends \
        nano \
        cron \
        supervisor \
    && apt-get clean


RUN mkdir /var/www
RUN chown www-data:www-data /var/www

# nodejs
RUN install -d -m 0755 -o www-data -g www-data /var/www/.nvm
USER www-data
ENV NVM_DIR=/var/www/.nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
RUN . "$NVM_DIR/nvm.sh" && nvm install v22.13.1
RUN . "$NVM_DIR/nvm.sh" && nvm use 22
RUN . "$NVM_DIR/nvm.sh" && nvm alias default 22
RUN . "$NVM_DIR/nvm.sh" && export NODE_VERSION="$(nvm current)"
ENV PATH="/var/www/.nvm/versions/node/v22.13.1/bin:${PATH}"
USER root

# composer
RUN set -eu; \
    EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"; \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"; \
    ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"; \
    if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; \
    then \
        >&2 echo 'ERROR: Invalid installer checksum'; \
        rm composer-setup.php; \
        exit 1; \
    fi; \
    php composer-setup.php --quiet --install-dir=/usr/local/bin --filename=composer; \
    RESULT=$?; \
    rm composer-setup.php; \
    exit $RESULT;

# XDebug
# RUN apt-get install -y --no-install-recommends \
#         libgl1 \
#         protobuf-compiler \
#         python3-dev \
#         python3-venv \
#         python3-pip \
#         wget \
#     && apt-get clean
RUN pecl install xdebug
#  && docker-php-ext-enable xdebug

COPY php.ini /usr/local/etc/php/php.ini
COPY mods.d/ /usr/local/etc/php/conf.d/

#miniconda
USER www-data
RUN mkdir -p /var/www/miniconda3
RUN wget "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-$(uname -m).sh" -O $HOME/miniconda3/miniconda.sh
RUN bash /var/www/miniconda3/miniconda.sh -b -u -p /var/www/miniconda3
RUN rm -rf /var/www/miniconda3/miniconda.sh
RUN /var/www/miniconda3/bin/conda init bash
# Accept ToS for required channels
RUN $HOME/miniconda3/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
RUN $HOME/miniconda3/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r
USER root

# crontab
RUN echo "*/1 * * * * www-data . /etc/environment; /usr/bin/php /data/bin/console oro:cron >> /data/var/logs/cron.log" >> /etc/cron.d/www-data-cron
RUN chmod 0644 /etc/cron.d/www-data-cron && crontab -u www-data /etc/cron.d/www-data-cron

# COPY start.sh /var/www/start.sh
# RUN chmod +x /var/www/start.sh
# CMD ["/var/www/start.sh"]

# ENV COMPOSER_ALLOW_SUPERUSER 1
# RUN install -d -m 0755 -o www-data -g www-data /var/www/.composer
# USER www-data
# RUN composer global config --no-plugins allow-plugins.symfony/flex true
# RUN composer global config --no-plugins allow-plugins.symfony/runtime true
# RUN composer global require composer/package-versions-deprecated
# RUN composer global require symfony/flex
# RUN composer global require symfony/runtime
# USER root

# EXPOSE 6006

RUN rm -rf /var/www/html \
    # && install -d -m 0755 -o www-data -g www-data /var/www \
    && install -d -m 0755 -o www-data -g www-data /var/www/.npm \
    && install -d -m 0755 -o www-data -g www-data /var/www/.cache \
    && chmod 0777 /tmp/
