css:
    inputs:
        # Settings
        - 'bundles/syntetiqmodel/themes/syntetiq/css/scss/primary-settings.scss'
    output: css/oro.css
#    auto_rtl_inputs:
#        - 'bundles/oro*/**'
#        - '~timepicker/jquery.timepicker.css'
